name: shopping
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1

  flutter:
    sdk: flutter
  provider: ^6.1.2
  http: ^1.2.2
  shimmer: ^3.0.0
  lottie: ^3.1.2
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/icon/
    - assets/fonts/montserrat/
    - assets/svg/empty/
    - assets/gifs/

